CREATE TABLE IF NOT EXISTS `METRIC` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Type` TEXT CHECK( Type IN ('node','func') ) NOT NULL,
    `Name` TEXT NOT NULL,
    `Value` REAL NULL,
    `Unit` TEXT NOT NULL,
    `Description` TEXT DEFAULT NULL,
    `ExpInstantID` INTEGER NOT NULL,
    `NodeID` INTEGER DEFAULT NULL,
    `FunctionID` INTEGER DEFAULT NULL,
        CONSTRAINT `ExpInstantID` FOREIGN KEY (`ExpInstantID`) REFERENCES `EXPERIMENT_INSTANT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `FunctionID` FOREIGN KEY (`FunctionID`) REFERENCES `FUNCTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `NodeIDMetic` FOREIGN KEY (`NodeID`) REFERENCES `NODE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);