CREATE TABLE IF NOT EXISTS `FUNCTION_TYPE` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `TypeName` TEXT NOT NULL UNIQUE,
    `Model` BLOB DEFAULT NULL,
    `Description` REAL NOT NULL,
    `MeanCpuCycles` REAL NOT NULL,
    `MeanRamUsageMb` REAL NOT NULL
);