CREATE TABLE IF NOT EXISTS `FUNCTION` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name` TEXT NOT NULL,
    `Description` TEXT NULL,
    `FunctionTypeID` INTEGER DEFAULT NULL,
        CONSTRAINT `FunctionTypeID` FOREIGN KEY (`FunctionTypeID`) REFERENCES `FUNCTION_TYPE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);