apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: openfaas
spec:
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30411
  type: NodePort
