# SPDX-License-Identifier: AGPL-3.0-or-later
# This YAML file overwrites the default values.yaml file in the HAProxy Helm
# chart.
#
# We run HAProxy in a master–worker model within a single container, alongside
# the Data Plane API operating in a sidecar container.
#
# Copyright 2025-2026 The DFaaS Authors. All rights reserved.
# This file is licensed under the AGPL v3.0 or later license. See LICENSE and
# AUTHORS file for more information.

# Set the HAProxy version, the same version is also for Data Plane API.
image:
  image: docker.io/haproxytech/haproxy-alpine
  tag: "3.2.6"

config: |
  # This is the basic HAProxy configuration, which overwrites the default
  # configuration from the Helm chart.
  global
    # Enable master-worker node to enable hot-reload feature.
    # See: https://docs.haproxy.org/3.2/configuration.html#3.1-master-worker
    master-worker

    # Enable Runtime API. This allows Data Plane API to make some changes
    # without requiding a reload. We expose the socket as TCP rather than UNIX
    # socket to allow Data Plane API to be in a different container than the
    # proxy.
    #
    # See: https://www.haproxy.com/documentation/haproxy-data-plane-api/installation/install-on-haproxy/
    # See: https://www.haproxy.com/documentation/haproxy-runtime-api/installation/
    stats socket ipv4@*:6666 mode 660 level admin expose-fd listeners
    log stdout format raw local0

  # An user is required by Dataplane API to work.
  userlist dataplaneapi
    user admin insecure-password admin

  defaults
    mode http
    option httplog
    log global
    timeout client 60s
    timeout connect 60s
    timeout server 60s

  # Allow Prometheus to scrape metrics.
  # See: https://www.haproxy.com/documentation/haproxy-configuration-tutorials/alerts-and-monitoring/prometheus/
  frontend prometheus
    bind :8405
    http-request use-service prometheus-exporter
    no log

  # This section will be overwritten by the DFaaS Agent with content that
  # depends on the selected offloading strategy.
  frontend main
    bind :80
    http-request return status 503 content-type "text/plain" string "This is a DFaaS node. Proxy is running, but the DFaaS agent is not!\n"

# The original HAProxy configuration cannot be modified, so we placed it in a
# different location.
configMount:
  mountPath: /usr/local/etc/haproxy/haproxy.init.readonly.cfg 
  subPath: haproxy.cfg        

initContainers:
  # Since the initial HAProxy configuration is read-only, we need to copy it to
  # a writable volume. Then, we must configure HAProxy and Data Plane API to use
  # the copied configuration file.
  - name: init-haproxy-config
    image: "busybox:musl"
    command: ["/bin/sh", "-c", "cp /opt/haproxy-config/haproxy.cfg /opt/haproxy-config-writable/haproxy.cfg && chmod 644 /opt/haproxy-config-writable/haproxy.cfg"]
    volumeMounts:
      - name: haproxy-config
        mountPath: /opt/haproxy-config
      - name: haproxy-config-writable
        mountPath: /opt/haproxy-config-writable

extraVolumes:
  # This volume will only contain the writable HAProxy configuration file.
  - name: haproxy-config-writable
    emptyDir: {}

extraVolumeMounts:
  # Mounted on the main container "haproxy".
  - name: haproxy-config-writable
    mountPath: /usr/local/etc/haproxy/config

args:
  # Read the configuration from the writable mount. Also enable master CLI as
  # UNIX socket, used by the Data Plane API. This is not exposed outside the
  # pod.
  #
  # See: https://docs.haproxy.org/3.3/management.html#9.4
  # See also: https://github.com/haproxytech/dataplaneapi/issues/391#issuecomment-3929209196
  defaults: ["-W", "-S", "/usr/local/etc/haproxy/config/haproxy-master.sock,mode,666,level,admin", "-db", "-f", "/usr/local/etc/haproxy/config/haproxy.cfg"]

# We expose HAProxy as a NodePort service to make it accessible from outside the
# cluster. As a result, other internal services (Runtime API, Data Plane API,
# and the Prometheus endpoint) are also exposed. While this may pose a security
# risk, keep in mind that DFaaS is a prototype.
#
# Note that the Runtime API is for the worker process, not the master (master
# CLI)!
service:
  type: NodePort

  # Let Prometheus to automatically scrape HAProxy metrics.
  # See: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8405"

  # We do not intend to expose the Prometheus port, but Kubernetes will still
  # map it to a random node port regardless.
  nodePorts:
    http: 30080
    dataplaneapi: 30555
    runtimeapi: 30666

# Required to enable Data Plane API sending UNIX signals to the HAProxy master
# node running on the main container.
shareProcessNamespace:
  enabled: true

# Start the Data Plane API in a dedicated container. The API connects to the
# master CLI UNIX socket exposed by HAProxy through the custom shared path between
# the two containers. Reload operations are performed via UNIX signals, which
# is why `shareProcessNamespace` is set to `true`.
sidecarContainers:
  - name: dataplaneapi
    image: docker.io/haproxytech/haproxy-alpine:3.2.6
    # We cannot run the Data Plane API directly, as we observed that it crashes
    # on the first attempt. Therefore, we need to execute it within a loop.
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          /usr/local/bin/dataplaneapi \
            --host 0.0.0.0 \
            --port 5555 \
            --log-level info \
            --master-runtime /usr/local/etc/haproxy/config/haproxy-master.sock \
            --userlist dataplaneapi \
            --config-file /usr/local/etc/haproxy/config/haproxy.cfg \
            --reload-cmd "pkill -SIGUSR2 haproxy" \
            --restart-cmd "pkill -SIGUSR1 haproxy" \
          && break
          echo "Dataplane API failed to start, retrying in 5s..."
          sleep 5
        done
    volumeMounts:
      - name: haproxy-config-writable
        mountPath: /usr/local/etc/haproxy/config

# These ports will be automatically included in the service object and exposed
# for external access (because we selected NodePort service type).
containerPorts:
  http: 80
  https: 443
  runtimeapi: 6666
  dataplaneapi: 5555
  prometheus: 8405
